// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://febmtmngilfvpkxcpaih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlYm10bW5naWxmdnBreGNwYWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTA5NDgsImV4cCI6MjA2NzM4Njk0OH0.zN0cvTlhAgieRbI4ifyN09BktkBg1G-GwhyO-_PGrwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});